### ISSUE TITLE
Methylene Blue not rendering correctly (And "Invalid SMILES structure")

### ISSUE THREAD

**Issue by Kira076** [lambdacasserole/avogadrio#15]
Using the version on avogadr.io currently, Methylene Blue does not render correctly using "methylthioninium chloride" nor "Methylthionine Chloride" as compound names and gives an "Invalid SMILES structure" error when attempting to render it using "CN(C)C1=CC2=C(C=C1)N=C3C=CC(=[N+](C)C)C=C3S2.[Cl-]".

I'm not at my primary computer so I have not attempted to run it myself on XAMP, so all I have to go off of is what's live on avogadr.io.

**Comment by lambdacasserole** [comment]
Thank you for bringing this to my attention! Fixed by #16. Tested and working [here](https://avogadr.io/?label=Methylene%20Blue&background=00305f&foreground=dbe1ff&smiles=CN(C)c1ccc2c(c1)sc-3cc(%3D%5BN%2B%5D(C)C)ccc3n2.%5BCl-%5D) without a problem.

**Comment by lambdacasserole** [comment]
Ah, this issue also highlights an error with how the app uses an external API to resolve compound names to SMILES structures. I'll open up a separate issue for that.
