### ISSUE TITLE
Needs minerals

### ISSUE THREAD

**Issue by icefoxen** [lambdacasserole/avogadrio#27]
For some reason `(K,Na)0-1(Ca,Na,Fe,Mg)2(Mg,Fe,Al)5(Al,Si)8O22(OH)2` doesn't seem to be a valid SMILES structure, and "hornblende" wasn't recognized as a valid mineral name.  Tried to google a SMILES structure index for minerals but I couldn't find one.

Forgive me since I'm not an organic-y guy, just a geologist.

**Comment by lambdacasserole** [comment]
Thank you for bringing this to my attention. It seems like the lack of support for this isn't in Avogadrio itself, but in the Indigo Cheminformatics Toolkit that does the rendering. If you put that SMILES string into http://opsin.ch.cam.ac.uk/ you'll get an error back too, which would suggest this would be better off on the Indigo issues page (https://github.com/epam/Indigo/issues). If it gets implemented over there we could bring that update across into Avogadrio no problem. Closing for now.

**Comment by dan2097** [comment]
SMILES does not cover minerals as they do not have molecular structures. The best SMILES can really do for infinite structures is describe the stoichiometry of the elements, which is fine for simple ionic compounds e.g. [Ca++].[Cl-].[Cl-], but this isn't a particularly useful way to represent a mineral.
