### ISSUE TITLE
Deoxyribonucleic acid displayed incorrectly 

### ISSUE THREAD

**Issue by remusmg** [lambdacasserole/avogadrio#32]
If you input "deoxyribonucleic acid", the result is a phenolphtalein molecule with an extra ether group connecting the two phenols ¯\_(ツ)_/¯

**Comment by lambdacasserole** [comment]
Super weird one there, well found! Unfortunately this seems to be an issue with an external service that Avogadrio uses to convert compound names into SMILES for rendering. Try putting “deoxyribonucleic acid” in here to see what I mean: https://cactus.nci.nih.gov/chemical/structure

**Comment by lambdacasserole** [comment]
Closing this, bug is external to the project.

**Comment by remusmg** [comment]
I see... So we're just gonna have to deal with it then. I don't even know
what I was expecting, because deoxyribonucleic acid is a class of compounds
rather than a specific compound. Kinda like putting "amino acid" in. The
code wouldn't know exactly what you mean.

Thanks for looking into it though, and lovely website concept/design. Cheers



În lun., 29 apr. 2019 la 16:35 Saul Johnson <notifications@github.com> a
scris:
