### ISSUE TITLE
Custom label + rotation = error

### ISSUE THREAD

**Issue by douglasrizzo** [lambdacasserole/avogadrio#37]
I just filled the "Custom label" field and changed the rotation to a value other than 0. Also, a strange artifact appeared in the label, which might be a clue to the origin of the issue.

![image](https://user-images.githubusercontent.com/2209364/88266507-b6658c80-cca5-11ea-8edd-0038bf7e427b.png)

**Comment by lambdacasserole** [comment]
Thank you for flagging this @douglasrizzo! Fixed by #38.
