### ISSUE TITLE
Ability to replace "Chiral" with custom text

### ISSUE THREAD

**Issue by MFernflower** [lambdacasserole/avogadrio#7]
Feature request

**Comment by lambdacasserole** [comment]
This is possible to do. The "Chiral" is the molecule renderer denoting the chiral centers in a molecule. If we disable this by passing `render-stereo-style=none` to Sourire these labels won't be shown. We can then pass `render-comment=customtext` to add a custom annotation to our molecule. This shouldn't be a lot of work, I'll get to it as soon as I can.

**Comment by lambdacasserole** [comment]
Thank you very much for taking the time to make this feature suggestion! It's now live with the merge of #9.
