### ISSUE TITLE
Invalid SMILES for C#C the SMILES for Acetylene.

### ISSUE THREAD

**Issue by namibj** [lambdacasserole/avogadrio#8]
Upon feeding C#C to the SMILES input I get a "Invalid SMILES structure!" error.

**Comment by lambdacasserole** [comment]
A regular expression in the CoffeeScript that validates SMILES structures has a lower limit on length (7 or longer accepted, others rejected). Fix incoming for this.

**Comment by lambdacasserole** [comment]
Thank you very much for letting me know about this. Fixed by #10 which is now live.
